app/__init__.py
from flask import Flask
from flask_login import LoginManager
from app.settings import SECRET_KEY
import dotenv


def create_app():
    app = Flask(__name__, template_folder='./templates')
    app.config.from_pyfile('settings.py')
    app.config['SECRET_KEY'] = f'{SECRET_KEY}'

    from app.persistance.db import init_db
    init_db(app)

    login_manager = LoginManager()
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(user_id):
        from app.controller.user_controller import get_user_by_email
        return get_user_by_email(user_id)

    from app.blueprints.open import bp_open
    app.register_blueprint(bp_open)

    from app.blueprints.user import bp_user
    app.register_blueprint(bp_user)

    from app.blueprints.admin import bp_admin
    app.register_blueprint(bp_admin, url_prefix='/admin/')

    return app


if __name__ == '__main__':
    dotenv.load_dotenv()
    create_app().run()

app/blueprints/admin/__init__.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import current_user, login_required
from bson.objectid import ObjectId

from app.controller import user_controller, news_sources_controller

bp_admin = Blueprint('bp_admin', __name__)


@bp_admin.before_request
def before_request():
    if not current_user.is_authenticated or not current_user.has_access('admin'):
        return redirect(url_for('bp_open.index'))


@bp_admin.get('/edit-users')
@login_required
def edit_users():
    users = user_controller.find_all_users()
    return render_template('edit_users.html', userlist=users)


@bp_admin.post('/delete-user')
@login_required
def edit_users_post():
    if request.method == 'POST':
        for user_id in request.form.getlist('user_checkbox'):
            user_controller.delete_user(ObjectId(user_id))
        return redirect(url_for('bp_admin.edit_users'))
    return 'Could not delete selected users'


@bp_admin.post('/add-user')
@login_required
def add_users_post():
    if request.method == 'POST':
        first_name = request.form.get('first_name')
        last_name = request.form.get('last_name')
        email = request.form.get('email')
        password = request.form.get('password')
        button = request.form.get('sign-up-button')

        from app.persistance.model import User
        user = User.find(email=email).first_or_none()

        if user is not None:
            flash('Email already exists')
            return redirect(url_for('bp_admin.edit_users'))

        user_controller.create_user(first_name, last_name, email, password)
        return redirect(url_for('bp_admin.edit_users'))
    return "Couldn't add new user"


@bp_admin.get('/edit-news')
@login_required
def edit_news_sources():
    all_news_sources = news_sources_controller.list_all_news_sources()
    return render_template('edit_news.html', news_list=all_news_sources)


@bp_admin.post('/edit-news')
@login_required
def edit_news_post():
    for news_name in request.form.getlist('news_checkbox'):
        from app.controller.news_sources_controller import deactivate_news_source
        deactivate_news_source(news_name)

    return redirect(url_for('bp_admin.edit_news_sources'))


@bp_admin.post('/activate-news')
@login_required
def activate_news_post():
    for news_name in request.form.getlist('news_checkbox'):
        from app.controller.news_sources_controller import activate_news_source
        activate_news_source(news_name)

    return redirect(url_for('bp_admin.edit_news_sources'))

app/blueprints/open/__init__.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from app.controller import user_controller

bp_open = Blueprint('bp_open', __name__)


@bp_open.get('/')
def index():
    return render_template('home.html')


@bp_open.get('/login')
def login():
    return render_template('login.html')


@bp_open.post('/login')
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
    if not user_controller.verify_user(email, password):
        flash("Wrong email or password")
        return redirect(url_for('bp_open.login'))

    user_controller.signin_user(email)

    return redirect(url_for('bp_user.newsfeed'))


@bp_open.get('/signup')
def signup():
    return render_template('signup.html')


@bp_open.post('/signup')
def signup_post():
    first_name = request.form.get('first_name')
    last_name = request.form.get('last_name')
    email = request.form.get('email')
    password = request.form.get('password')

    from app.persistance.model import User
    user = User.find(email=email).first_or_none()

    if user is not None:
        flash('Email already exists')
        return redirect(url_for('bp_open.signup'))

    user_controller.create_user(first_name, last_name, email, password)
    return redirect(url_for('bp_open.login'))


@bp_open.get('/about')
def about():
    return redirect(url_for('bp_open.index', _anchor='about'))

app/blueprints/user/__init__.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_required, logout_user, current_user


bp_user = Blueprint('bp_user', __name__)


@bp_user.get('/account')
@login_required
def profile():
    from app.controller.news_sources_controller import list_all_news_sources
    news = list_all_news_sources()
    return render_template('profile.html', news_list=news)


@bp_user.post('/account')
@login_required
def save_selections():
    selections = request.form.getlist('news_checkbox')
    if selections == None:
        return redirect(url_for('bp_user.profile'))

    from app.controller.news_sources_controller import delete_all_news_sources_from_user
    delete_all_news_sources_from_user(current_user)

    from app.controller.news_sources_controller import add_news_source
    add_news_source(current_user, selections)
    return redirect(url_for('bp_user.profile'))


@bp_user.get('/newsfeed')
@login_required
def newsfeed():
    if not current_user.news_sources or current_user.news_sources == [None]:
        return render_template('newsfeed.html', news='none')

    from app.controller.news_sources_controller import get_all_news_sources
    news = get_all_news_sources()

    return render_template('newsfeed.html', news=news)


@bp_user.get('/sign-out')
@login_required
def signout():
    logout_user()
    return redirect(url_for('bp_open.index'))

app/persistance/db/__init__.py
from abc import ABC
from pymongo import MongoClient

client = None
db = None


def init_db(app):
    global client, db
    username = app.config['DB_USER']
    password = app.config['DB_PASSWORD']
    host = app.config['DB_HOST']
    port = int(app.config["DB_PORT"])
    database = app.config['DB_NAME']
    client = MongoClient(f'mongodb://{username}:{password}@{host}:{port}')
    db = client[database]


class ResultList(list):
    def first_or_none(self):
        return self[0] if len(self) > 0 else None

    def last_or_none(self):
        return self[-1] if len(self) > 0 else None


class Document(dict, ABC):
    collection = None

    def __init__(self, data):
        super().__init__()
        if '_id' not in data:
            self._id = None
        self.__dict__.update(data)

    def __repr__(self):
        return '\n'.join(f'{k} = {v}' for k, v in self.__dict__.items())

    def save(self):
        if not self._id:
            del (self.__dict__['_id'])
            return self.collection.insert_one(self.__dict__)
        else:
            return self.collection.replace_one({'_id': self._id}, self.__dict__)

    def delete_field(self, field):
        self.collection.update_one({'_id': self._id}, {"$unset": {field: ""}})

    @classmethod
    def insert_many(cls, items):
        for item in items:
            cls(item).save()

    @classmethod
    def all(cls):
        return [cls(item) for item in cls.collection.find({})]

    @classmethod
    def find(cls, **kwargs):
        return ResultList(cls(item) for item in cls.collection.find(kwargs))

    @classmethod
    def delete(cls, **kwargs):
        cls.collection.delete_many(kwargs)

app/persistance/model/__init__.py
from app.persistance.db import db, Document

ACCESS = {
    'guest': 0,
    'user': 1,
    'admin': 2
}


class User(Document):
    collection = db.users

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return self.email

    def has_access(self, level):
        return ACCESS[self.accesslevel] >= ACCESS[level]


class News(Document):
    collection = db.news

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flask Project</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.3/css/bulma.min.css" integrity="sha512-IgmDkwzs96t4SrChW29No3NXBIBv8baW490zk5aXvhCD8vuZM3yUSkbyTBcXohkySecyzIrUwiF/qV0cuPcL3Q==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />
    <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    {% block head %}

    {% endblock %}
</head>
<body>
    <div class="hero-head">
        <nav id="navbar-hero" class="navbar">
            <div class="container">
                <div class="navbar-menu">
                    <a href="{{ url_for('bp_open.index') }}" class="navbar-item">Home</a>
                    {% if current_user.is_authenticated %}
                        <a href="{{ url_for('bp_user.newsfeed') }}" class="navbar-item">Feed</a>
                        <a href="{{ url_for('bp_user.profile') }}" class="navbar-item">Account</a>
                        {% if current_user.has_access('admin') %}
                            <div class="navbar-item has-dropdown is-hoverable">
                                <a id="dropdown-link" class="navbar-link">Admin</a>
                                <div class="navbar-dropdown">
                                    <a href="{{ url_for('bp_admin.edit_users') }}" class="dropdown-item">Edit Users</a>
                                    <a href="{{ url_for('bp_admin.edit_news_sources') }}" class="dropdown-item">Edit News Sources</a>
                                </div>
                            </div>
                        {% endif %}
                        <div class="navbar-end">
                        <a href="{{ url_for('bp_user.signout') }}" class="navbar-item">Sign out</a>
                        </div>
                    {% else %}
                        <a href="{{ url_for('bp_open.about') }}" class="navbar-item">About</a>
                        <a href="{{ url_for('bp_open.signup') }}" class="navbar-item">Sign up</a>
                        <div class="navbar-end">
                            <a href="{{ url_for('bp_open.login') }}" class="navbar-item">Login</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </nav>
    </div>
{% block content %}

{% endblock %}

{% block scripts %}

{% endblock %}


{% block footer %}

{% endblock %}

</body>
</html>

app/templates/edit_news.html
{% extends 'base.html' %}

{% block title %}Edit News Sources{% endblock %}

{% block content %}
    <section class="hero is-light is-medium has-text-centered">
        <div class="hero-body">
            <p class="title">Edit News Sources</p>
            <p class="subtitle">Manage news sources</p>
        </div>
    </section>
    <section class="hero">
        <form class="hero" action="{{ url_for('bp_admin.edit_news_post') }}" method="POST">
            <nav id="admin-submenu" class="navbar">
                <div class="hero">
                    <div id="edit-user-buttons" class="navbar">
                        <button id="activate-news" class="button" type="submit" formaction="/admin/activate-news">
                            <strong>Activate selected</strong>
                        </button>
                        <button id="delete-news" class="button is-danger" type="submit">
                            <strong>Deactivate selected</strong>
                        </button>
                    </div>
                </div>
            </nav>
        <table id="news_table" class="table is-striped">
            <thead>
            <th><input type="checkbox" id="checkall"></th>
            <th>#</th>
            <th>Shown to users</th>
            </thead>
            <tbody>
            {% for news_place in news_list %}
                <tr>
                    <th><input type="checkbox" value="{{ news_place.name }}" name="news_checkbox"></th>
                    <td>{{ news_place.name }}</td>
                    {% if news_place.is_available %}
                        <td>Yes</td>
                    {% else %}
                        <td>No</td>
                    {% endif %}
                </tr>
            {% endfor %}

            </tbody>
        </table>
        </form>
    </section>
{% endblock %}

{% block scripts %}
    <script src="{{ url_for('static', filename='/js/news_checkboxes.js') }}"></script>
{% endblock %}

app/templates/edit_users.html
{% extends 'base.html' %}

{% block title %}Edit users{% endblock %}

{% block content %}
    <section id="header-section" class="hero is-light is-medium has-text-centered">
        <div class="hero-body">
            <p class="title">Edit Users</p>
            <p class="subtitle">Manage users from the database</p>
        </div>
    </section>
    <section class="hero">
        <form class="hero" action="{{ url_for('bp_admin.edit_users_post') }}" method="POST">
            <nav id="admin-submenu" class="navbar">
                <div class="hero">
                    <div class="navbar">
                        <a id="add-user" class="js-modal-trigger button" data-target="add-user-modal">
                            <strong>Add user</strong>
                        </a>
                        <button id="delete-user" class="button is-danger" type="submit">
                            <strong>Delete Selected</strong>
                        </button>
                    </div>
                </div>
            </nav>
            <table id="user_table" class="table is-striped">
                <thead>
                <th><input type="checkbox" id="checkall"></th>
                <th>#</th>
                <th>Firstname</th>
                <th>Lastname</th>
                <th>Email</th>
                <th>Type</th>
                <th>Last visit</th>
                </thead>
                <tbody>
                {% for user in userlist %}
                    <tr>
                        <th><input type="checkbox" value="{{ user._id }}" name="user_checkbox"></th>
                        <th>{{ loop.index }}</th>
                        <td>{{ user.first_name }}</td>
                        <td>{{ user.last_name }}</td>
                        <td>{{ user.email }}</td>
                        <td><strong>{{ user.accesslevel }}</td>
                        <td>{{ user.last_signin }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </form>
        <div id="add-user-modal" class="modal">
            <div class="modal-background"></div>
            <div class="modal-content">

                <form class="box" action="{{ url_for('bp_admin.add_users_post') }}" method="POST">
                    <div class="field">
                        <label class="label">First name</label>
                        <div class="control">
                            <input class="input" name="first_name" type="text" placeholder="Alice">
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Last name</label>
                        <div class="control">
                            <input class="input" name="last_name" type="text" placeholder="Johnson">
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Email</label>
                        <div class="control">
                            <input class="input" name="email" type="email" placeholder="alice.johnson@email.com" required>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Password</label>
                        <div class="control">
                            <input class="input" name="password" type="password" placeholder="************" required>
                        </div>
                    </div>

                    <button type="submit" name="sign-up-button" class="button is-danger">Add user</button>
                </form>
            </div>
            <button class="modal-close is-large" aria-label="close"></button>
        </div>
    </section>
{% endblock %}

{% block scripts %}
    <script src="{{ url_for('static', filename='/js/checkboxes.js') }}"></script>
    <script src="{{ url_for('static', filename='/js/modal.js') }}"></script>

{% endblock %}

app/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <section class="hero is-fullheight">
        <div id="splash-screen" class="hero-body has-text-centered">
            <div class="container">

            </div>
        </div>
    </section>

    <section id="about" class="section is-large has-text-centered">
      <h1 class="title">About our service</h1>
      <p>
          Lorem ipsum dolor sit amet, at mei phaedrum philosophia. Qui antiopam prodesset an, usu modus qualisque ea.
          Mel omnis doctus prodesset in, esse graece ut cum, eu dictas recusabo eum. Errem incorrupte ne has.
          Reque minim bonorum vis te, dico dicam voluptaria nam ex, te sale splendide pro. Usu at sumo justo graece,
          no mel debet clita feugait, eum rationibus inciderint in.
          Mandamus postulant vel no, ea mea fugit etiam lobortis.
          Ad possim indoctum mel, cu per ignota veritus. Tota nemore imperdiet ea pro, ludus decore cotidieque ad per.
          Vim ex insolens scripserit, id eos vocibus verterem mnesarchum, id sit erat ubique.
          Te inani dicit officiis per, nam justo errem ad, at mollis phaedrum prodesset duo.
      </p>
    </section>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<section class="hero is-fullheight">
    <div class="hero-body">
        <div class="column is-4 is-offset-4">
            <div class="container">
                <p class="title has-text-centered">Enter details</p>

                <form class="box" action="/login" method="POST">
                    {% with messages = get_flashed_messages() %}
                        {% if messages %}
                            {% for message in messages %}
                                <div class="notification is-danger">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                    <div class="field">
                        <label class="label">Email</label>
                        <div class="control">
                            <input class="input" name="email" type="email" placeholder="e.g. alex@example.com">
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Password</label>
                        <div class="control">
                            <input class="input" name="password" type="password" placeholder="********">
                        </div>
                    </div>
                    
                    <button type="submit" class="button is-danger">Login</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

app/templates/newsfeed.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <section class="hero is-fullheight-with-navbar">
        <div id="feed" class="column is-three-fifths is-offset-one-fifth">
            <div class="container is-fullheight">
                <div id="news-feed" class="hero">
                    <div class="card">
                        {% if news != 'none' %}
                            {% for title, desc, image, link in news %}
                                <div class="card-image">
                                    <figure>
                                        <img id="feed-image" src="{{ image }}" alt="">
                                    </figure>
                                </div>
                                <div class="content">
                                    <p class="title is-size-3">{{ title }}</p>
                                    <p class="is-size-6">{{ desc }}</p>
                                </div>
                                <footer>
                                    <hr>
                                    <a href="{{ link }}" class="card-footer-item is-size-6 is-black"
                                       rel="noreferrer noopener"
                                       target="_blank">Link to article</a>
                                </footer>
                                <hr>
                            {% endfor %}
                        {% else %}
                            No news sources selected! Please select them in your profile page.
                        {% endif %}
                    </div>
                </div>
                <hr>
            </div>
        </div>
        </div>
    </section>
{% endblock %}

{% block scripts %}
    <script src="{{ url_for('static', filename='js/auto_refresh.js') }}"></script>
{% endblock %}

app/templates/profile.html
{% extends 'base.html' %}

{% block title %}Profile page{% endblock %}

{% block content %}
    <div class="hero">
        <div class="hero-body">
            <div class="column is-one-fifth">
                <form class="box" action="{{ url_for('bp_user.save_selections') }}" method="POST">
                    <ul>
                        {% for news_place in news_list %}
                            <li>
                                {% if news_place.is_available %}
                                    {% if news_place.name in current_user.news_sources %}
                                        <input type="checkbox" id="{{ news_place.name }}" name="news_checkbox" value="{{ news_place.name }}" checked>
                                        <label for="{{ news_place.name }}">{{ news_place.name }}</label>
                                    {% else %}
                                        <input type="checkbox" id="{{ news_place.name }}" name="news_checkbox" value="{{ news_place.name }}">
                                        <label for="{{ news_place.name }}">{{ news_place.name }}</label>
                                    {% endif %}

                                {% else %}
                                    <input type="checkbox" id="{{ news_place.name }}" name="news_checkbox" value="{{ news_place.name }}" disabled="disabled">
                                    <label for="{{ news_place.name }}">{{ news_place.name }}</label>
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ul>

                    <button id="profile-save-button" class="button is-light">Save</button>
                </form>
            </div>
            <div class="column">
                <div class="container">
                    <p class="title has-text-centered">Welcome to your profile {{ current_user.first_name }}</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/signup.html
{% extends 'base.html' %} {% block title %}Sign Up{% endblock %} {% block
content %}
<section class="hero is-fullheight">
    <div class="hero-body">
        <div class="column is-4 is-offset-4">
            <div class="container">
                <p class="title has-text-centered">Create an account</p>

                <form class="box" action="{{ url_for('bp_open.signup_post') }}" method="POST">
                    {% with messages = get_flashed_messages() %}
                        {% if messages %}
                            {% for message in messages %}
                                <div class="notification is-danger">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                    <div class="field">
                        <label class="label">First name</label>
                        <div class="control">
                            <input class="input" name="first_name" type="text" placeholder="Alice">
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Last name</label>
                        <div class="control">
                            <input class="input" name="last_name" type="text" placeholder="Johnson">
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Email</label>
                        <div class="control">
                            <input class="input" name="email" type="email" placeholder="alice.johnson@email.com">
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Password</label>
                        <div class="control">
                            <input class="input" name="password" type="password" placeholder="************" required>
                        </div>
                    </div>

                    <button type="submit" class="button is-danger">Sign up</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}